---
- name: bootstrap ubuntu
  hosts: ubuntu
  become: true
  become_user: root
  gather_facts: false
  roles:
    - role: ubuntu-bootstrap

- name: setup jumphost
  hosts: jumphost
  become: true
  become_user: root
  roles:
    - role: docker
    - role: admin-tools
