    prometheus:
        image: prom/prometheus:v1.3.1
        hostname: prometheus
        volumes:
            - /srv/prometheus/prometheus:/prometheus
            - ./prometheus/config:/etc/prometheus
        command:
            - -config.file=/etc/prometheus/prometheus.yml
            - -alertmanager.url=http://alertmanager:9093
            - -storage.local.memory-chunks=130050
            - -storage.local.series-file-shrink-ratio=0.3
            - -storage.local.retention=1800h
        links:
            - node-exporter
            - alertmanager
        labels:
            - "traefik.backend=prometheus"
            - "traefik.frontend.rule=Host:prometheus.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9090"
    node-exporter:
        image: prom/node-exporter:0.12.0
        labels:
            - "traefik.backend=node-exporter"
            - "traefik.frontend.rule=Host:node-exporter.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9100"
    grafana:
        image: grafana/grafana:3.1.1
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
#            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_BASIC_ENABLED=false
#            - GF_AUTH_PROXY_ENABLED=true
#            - GF_AUTH_ANONYMOUS_ENABLED=true
#            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        links:
            - prometheus
        volumes:
            - /srv/prometheus/grafana:/var/lib/grafana
        labels:
            - "traefik.backend=grafana"
            - "traefik.frontend.rule=Host:grafana.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=3000"
    alertmanager:
        image: prom/alertmanager:v0.5.0
#        command:
#            - '-config.file=/alertmanager.yml'
        volumes:
#            - ./prometheus/alertmanager.yml:/alertmanager.yml
            - /srv/prometheus/alertmanager:/alertmanager
        labels:
            - "traefik.backend=alertmanager"
            - "traefik.frontend.rule=Host:alertmanager.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9093"
