    prometheus:
        image: prom/prometheus:v1.3.1
        hostname: prometheus
        volumes:
            - /srv/prometheus/prometheus:/prometheus
            - ./prometheus/config:/etc/prometheus
        command:
            - -config.file=/etc/prometheus/prometheus.yml
            - -alertmanager.url=http://alertmanager:9093
            - -storage.local.memory-chunks=130050
            - -storage.local.series-file-shrink-ratio=0.3
            - -storage.local.retention=1800h
        links:
            - node-exporter
            - alertmanager
        labels:
            - "traefik.backend=prometheus"
            - "traefik.frontend.rule=Host:prometheus.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9090"
    node-exporter:
        image: prom/node-exporter:0.12.0
        labels:
            - "traefik.backend=node-exporter"
            - "traefik.frontend.rule=Host:node-exporter.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9100"
    alertmanager:
        image: prom/alertmanager:v0.5.0
#        command:
#            - '-config.file=/alertmanager.yml'
        volumes:
#            - ./prometheus/alertmanager.yml:/alertmanager.yml
            - /srv/prometheus/alertmanager:/alertmanager
        labels:
            - "traefik.backend=alertmanager"
            - "traefik.frontend.rule=Host:alertmanager.${DOMAIN_NAME}"
            - "traefik.enable=true"
            - "traefik.port=9093"
